### ISSUE TITLE
Show the members balance on their account page

### ISSUE THREAD

**Issue by ArthurGuy** [ArthurGuy/BBMembershipSystem#165]
This should appear at the top of the page along with the other pieces of information.

**Comment by adamstrawson** [comment]
Where about's do you see this sitting?

**Comment by ArthurGuy** [comment]
Not really sure, the top bar is a bit of a dumping ground for these things so probably somewhere there.
Perhaps next to the subscription expiry date or the subscription amount value.
Not sure how these will work when reduced to mobile view though.

Thanks for you help with these.
