### ISSUE TITLE
Convert from Less to Scss

### ISSUE THREAD

**Issue by mikestreety** [ArthurGuy/BBMembershipSystem#174]
Spoke about this briefly - did you want me to have a look at converting the CSS from Less to Scss?

**Comment by ArthurGuy** [comment]
Please do, I did the same thing to another smaller project last night and it worked perfectly.

This has a double set of script generation going on but it's a good indicator of how it can work within the Laravel folder structure.
https://github.com/ArthurGuy/DataStore/blob/master/gulpfile.js

Definitely not a must though so I am happy to let you run with this.

**Comment by mikestreety** [comment]
Perfect - will give me a chance to get to know the CSS a bit more!
