### ISSUE TITLE
BBMS Needs URL links to the google forum groups

### ISSUE THREAD

**Issue by OricTosh** [ArthurGuy/BBMembershipSystem#78]
Placing the following information upon a page within BBMS as clickable links, which open in a new window/tab would help new/old members find the group that they wish to take part in.

https://groups.google.com/forum/#!forum/buildbrighton-discuss             <private group forum>
https://groups.google.com/forum/#!forum/bb-audio                                <private group forum>
https://groups.google.com/forum/#!forum/brighton-hackspace-members  <private group forum>
https://groups.google.com/forum/#!forum/brightonhackerspace               <public group forum>
https://groups.google.com/d/forum/bb-machinists                                 <private group forum>

Private means you need to make a request to the owner of that group to post/read messages
Public means everyone can read/post messages.
As far as i'm aware the information above is upto date, 

You could also state the owner of each group.
I'm aware that Alex setup the BB-Audio group, Mike P the BB-machinists, Seb set-up the discuss group, not sure about the other group but the people that set them up are the owners of them. The managers of the groups should be able to see who the owner is.

**Comment by ArthurGuy** [comment]
New resources section created
