### ISSUE TITLE
Add useful links section to Tools pages

### ISSUE THREAD

**Issue by scropp** [ArthurGuy/BBMembershipSystem#79]
The idea here being to allow those registered as trainers to add links to relevant information like

* Manufacturers homepage
* induction manual
* wiki page

That sort of thing.

These could be marked as 

* visible to all (eg. the glossy brochure so show those who are not trained what it is that we are offering)
* Only those who have paid their maint fees and have had the safety training (eg how to use the device)
* Only trainers (not sure about this one. Might be useful if you have some how to teach style notes, otherwise not needed)

**Comment by ArthurGuy** [comment]
mostly done as part of the new equipment pages
