### ISSUE TITLE
Log downtime in the laser usage log

### ISSUE THREAD

**Issue by scropp** [ArthurGuy/BBMembershipSystem#85]
When the laser cutter is unavailable allow a member of the laser  team (or a laser trainer?) to set the laser as unavailable and then available again when fixed. 

This is logged in the usage log so a user can see if it is out of action and cannot activate it when it is out of action.

We can also extract valuable metrics from the log such as MTBF and the total time the machine has been available to use,

**Comment by ArthurGuy** [comment]
Equipment team members can update the status through the BBMS locking down the laser cutter.
The new RFID hardware will allow for better tracking of device usage
